FROM golang:1.12.0-alpine3.9 as builder
ENV CGO_ENABLED 0
ADD . /go/src/descum/service/sn-instagram/

RUN apk add --no-cache git
RUN go get github.com/gorilla/mux

RUN env GOOS=linux GOARCH=amd64 go build -o /server descum/service/sn-instagram

###############

FROM envoyproxy/envoy-alpine-dev:latest

WORKDIR /

COPY --from=builder /server /

CMD ./server & envoy -c /etc/service-envoy.yaml --service-cluster service${SERVICE_NAME}