FROM golang:1.12.0-alpine3.9 as builder
ENV CGO_ENABLED 0
ADD . /go/src/descum/service/sn-facebook/

RUN apk add --no-cache git
RUN go get github.com/gorilla/mux

RUN go build -gcflags "all=-N -l" -o /server descum/service/sn-facebook

RUN go get github.com/derekparker/delve/cmd/dlv

###############

FROM envoyproxy/envoy-alpine-dev:latest
EXPOSE 40000

WORKDIR /

COPY --from=builder /server /
COPY --from=builder /go/bin/dlv /

CMD /dlv --listen=:40001 --headless=true --api-version=2 --accept-multiclient exec ./server & envoy -c /etc/service-envoy.yaml --service-cluster service${SERVICE_NAME}